### ISSUE TITLE
the green spectum is behind the modal

### ISSUE THREAD

**Issue by kittenvr** [parzival-space/powercord-pspectrum#10]
https://user-images.githubusercontent.com/103120356/184603115-ae4aea62-291c-4098-8e17-f3d94046e135.mp4

**Comment by parzival-space** [comment]
You can set in your custom css something like this.

```css
#pspectrum-visualizer {
  z-index: 10; /* or something else */
}
```

If not, please send me your theme.
