### ISSUE TITLE
Opacity Adjustment Setting

### ISSUE THREAD

**Issue by parzival-space** [parzival-space/powercord-pspectrum#9]
This issue is for tracking the Opacity Adjustment feature.

See: <a href="https://github.com/parzival-space/powercord-pspectrum/pull/8">Name Change and Feature Request</a>

**Comment by parzival-space** [comment]
I don't have enough time to work on it right now. 
Pull requests are welcome. 
In the meantime, you can easily change the opacity with custom css like below:

```css
#pspectrum-visualizer {
  opactiy: 0.5; /* 0 - 1 */
}
```
